"""init

Revision ID: 9517c063e1b3
Revises: 
Create Date: 2022-05-12 12:48:36.092972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9517c063e1b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_inner',
    sa.Column('id', sa.String(length=32), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='内部用ID'),
    sa.Column('update_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.PrimaryKeyConstraint('id'),
    schema='inner',
    comment='for inner'
    )
    op.create_index(op.f('ix_inner_m_inner_id'), 'm_inner', ['id'], unique=False, schema='inner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inner_m_inner_id'), table_name='m_inner', schema='inner')
    op.drop_table('m_inner', schema='inner')
    # ### end Alembic commands ###
